version: '3.8'

services:
  django_freelance_exchange:
    container_name: django_freelance_exchange
    build:
      context: .
      dockerfile: config/django/Dockerfile
    restart: on-failure
    networks:
      - demo
    expose:
      - 8001
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    depends_on:
      - db_freelance_exchange
    links:
      - db_freelance_exchange

  nginx_freelance_exchange:
    container_name: nginx_freelance_exchange
    build: 
      context: .
      dockerfile: config/nginx/Dockerfile
    restart: on-failure
    networks:
      - demo
    expose:
      - 80
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    links:
      - django_freelance_exchange

  db_freelance_exchange:
    container_name: db_freelance_exchange
    image: postgres:15
    networks:
      - demo
    expose:
      - 5432
    env_file:
      - freelance_exchange/.env
    volumes:
      - ./db:/var/lib/postgresql:z

networks:
  demo:
    # driver: bridge
    external: true
